use_frameworks!

target 'BlockDataSource_Example' do
  pod 'BlockDataSource', :path => '../'

  target 'BlockDataSource_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
